apiVersion: v1
kind: Service
metadata:
  name: apollo-kubernetes-demo-service
spec:
  selector:
    app: apollo-kubernetes-demo
  ports:
    - protocol: TCP
      port: 80          # External port
      targetPort: 8100  # Port inside the container
  type: LoadBalancer    # Use "NodePort" if you don't have a LoadBalancer available
